# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraMccExServiceExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'RTMTokenBuilder', "1.0.0"

  pod 'AgoraRtcEngine_Special_iOS', '4.1.1.23'
  pod "Zip"
  pod 'AgoraComponetLog', "0.0.2"
end

